name: "Build and upload package"
description: "Builds and uploads a Godot package to the archive"

inputs:
  godot_version:
    description: "Godot Version"
    required: true
    default: 3.4
  export_template:
    description: "Name of the export template to build"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Export Templates
      shell: bash
      run: |
        mkdir -v -p ~/.local/share/godot/templates
        mv /root/.local/share/godot/templates/${{ inputs.godot_version }}.stable ~/.local/share/godot/templates/${{ inputs.godot_version }}.stable
    - name: Build
      shell: bash
      run: |
        mkdir -v -p "build"
        godot -v --export "${{ inputs.export_template }}"
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.export_template }}
        path: build/
